# Tmux Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'wfxr/tmux-power'

set -g mouse on
set-option -g default-shell $HOME/.cargo/bin/nu
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
set-window-option -g mode-keys vi
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# Prefix key
unbind C-b
set-option -g prefix M-s

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Status bars
set -g status-right '[#S] #(pomodoro status)'
set-option -g status-interval 1
bind s set-option -g status
bind C-s set-option -g status
set-window-option -g window-status-style fg=magenta
set-window-option -g window-status-style bg=default

# Reload tmux config
bind -n M-r source-file ~/.tmux.conf

# Colors
set -ag terminal-overrides ",alacritty:RGB"
set -g @tmux_power_theme 'moon'

# Tmux plugin manager, keep this at the bottom
run "~/.tmux/plugins/tpm/tpm"

