"Vim plugins
call plug#begin('~/.vim/plugged')
Plug 'editorconfig/editorconfig-vim'
Plug 'mattn/emmet-vim'
Plug 'w0rp/ale'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'preservim/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'ryanoasis/vim-devicons'
Plug 'scrooloose/nerdcommenter'
Plug 'ntk148v/vim-horizon'
Plug 'itchyny/lightline.vim'
Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }, 'for': ['markdown', 'vim-plug']}
call plug#end()

"Settings
set encoding=UTF-8
set whichwrap+=<,>,[,]
let g:ale_fixers = {
 \ 'javascript': ['eslint'],
 \ 'typescript': ['eslint'],
 \ 'css': ['prettier'],
 \ 'scss': ['prettier'],
 \ }
set noshowmode

"Theme
syntax on
set termguicolors
colorscheme horizon
let g:ale_sign_error = '✘'
let g:ale_sign_warning = '⚠️'
let g:ale_fix_on_save = 1
highlight ALEErrorSign ctermbg=NONE ctermfg=red
highlight ALEWarningSign ctermbg=NONE ctermfg=yellow

"right arrow next line basically
set whichwrap+=<,>,[,]

"coc config
let g:coc_global_extensions = [
    \ "coc-snippets",
    \ "coc-pairs",
    \ "coc-tsserver",
    \ "coc-eslint",
    \ "coc-prettier",
    \ "coc-json",
    \ "coc-git",
    \ ]
"Nerd tree
let g:NERDTreeIgnore = ['^node_modules$']

nnoremap <C-n> :NERDTreeToggle<CR>
nnoremap <C-f> :NERDTreeFind<CR>

"Nerd Commenter
vmap <C-_> \c<space><CR>gv
nmap <C-_> \c<space><CR>
imap <C-_> <esc>\c<space><CR>i

"Prettier
command! -nargs=0 Prettier :CocCommand prettier.formatFile
vmap <leader>f :Prettier<CR>
nmap <leader>f :Prettier<CR>

"Lightline status
function! LightlineGitStatus() abort
  let blame = get(g:, 'coc_git_status', '')
  " return blame
  return winwidth(0) > 120 ? blame : ''
endfunction
let g:lightline = {
    \ 'colorscheme': 'one',
    \ 'active': {
    \   'left': [
    \     [ 'mode', 'paste' ],
    \     [ 'ctrlpmark', 'git', 'diagnostic', 'cocstatus', 'filename', 'method' ]
    \   ],
    \   'right': [
    \     [ 'filetype', 'fileencoding', 'lineinfo', 'percent' ],
    \     [ 'status' ],
    \   ],
    \ },
    \ "component_function": {
    \    "status": "LightlineGitStatus",
    \ },
\ }

"Markdown preview
nmap <C-p> <Plug>MarkdownPreviewToggle
