export ZSH="$HOME/.oh-my-zsh"

plugins=(git docker zsh-lazyload zsh-autosuggestions)
zmodload zsh/zprof

export PATH="$HOME/.local/bin:$PATH"
# https://starship.rs/
eval "$(starship init zsh)"
# VIM ftw
export EDITOR="nvim"
export VISUAL="nvim"
# Git alias shortcuts
alias gbr="git branch"
alias gps="git push"
alias gpl="git pull"
alias gcm="git commit -m"
alias gcam="git commit -a -m"
alias gst="git status"
alias gdf="git diff"
alias gad="git add"
alias gch="git checkout"
alias gchb="git checkout -b"
# Open git repo url in browser
alias gro="xdg-open $(git config --get remote.origin.url)"
# Comment out if using normal docker
alias docker="podman"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
