source ~/.zplug/init.zsh

# zsh plugins
zplug "Aloxaf/fzf-tab", use:"*.zsh"

zmodload zsh/zprof
export PATH="$HOME/.local/bin:$PATH"
# https://starship.rs/
eval "$(starship init zsh)"
# VIM ftw
export EDITOR="nvim"
export VISUAL="nvim"
# Git alias shortcuts
alias gbr="git branch"
alias gps="git push"
alias gpl="git pull"
alias gcm="git commit -m"
alias gcam="git commit -a -m"
alias gst="git status"
alias gdf="git diff"
alias gad="git add"
alias gch="git checkout"
alias gchb="git checkout -b"
# Open git repo url in browser
alias gro="xdg-open $(git config --get remote.origin.url)"

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# Then, source plugins and add commands to $PATH
zplug load --verbose

for file in ../user/*.zsh; do
    if [[ -a "$file" ]]; then
        source "$file"
    fi
done

