#Inserts a blank line between shell prompts
#command_timeout = 2500
format = """$all[->](bold #0096FF) """

# Disable the blank line at the start of the prompt
add_newline = false

[cmd_duration]
disabled = false
min_time = 500
format = "Took [$duration](bold yellow)"

[character]
disabled = true

[git_status]
disabled = false
ignore_submodules = true

