#Inserts a blank line between shell prompts
#command_timeout = 2500
format = """$all[->](bold #0096FF) """

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = true

[cmd_duration]
disabled = false
min_time = 500
format = "Took [$duration](bold yellow)"

[character]
disabled = true
