#!/bin/zsh
# BSPWM Config

bspc rule -r "*"

## Autostart
pkill nm-applet
pkill picom
pkill sxhkd
pkill dunst
pkill feh
pkill polybar
pkill flameshot

nm-applet &
picom &
SXHKD_SHELL="$SHELL" sxhkd &
dunst &
feh --bg-scale --no-fehbg ~/wall.png &
polybar main &
flameshot &

## Monitors
~/monitors

## Global settings

bspc config pointer_modifier shift
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true
bspc config history_aware_focus true
bspc config normal_border_color "#4c566a"
bspc config active_border_color "#1e1e1e"
bspc config focused_border_color "#406ea5"
bspc config presel_feedback_color "#327bd1"
bspc config urgent_border_color "#dd2727"

### Desktop settings
bspc config top_padding 32
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config window_gap 10

### Rules
bspc rule -a mpv state=fullscreen

