source ~/.zplug/init.zsh

# zsh plugins
zplug "Aloxaf/fzf-tab", use:"*.zsh"

zmodload zsh/zprof
export SHELL=$(which zsh)
# https://starship.rs/
eval "$(starship init zsh)"
# VIM ftw
export EDITOR="nvim"
export VISUAL="$EDITOR"
export GIT_EDITOR="$EDITOR"
# Git alias shortcuts
alias gbr="git branch"
alias gps="git push"
alias gpl="git pull"
alias gcm="git commit -m"
alias gcam="git commit -a -m"
alias gst="git status"
alias gdf="git diff"
alias gad="git add"
alias gch="git checkout"
alias gchb="git checkout -b"
# Open git repo url in browser
alias gro="xdg-open $(git config --get remote.origin.url)"

#source ./keybindings.sh

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo
        zplug install
    fi
fi

# Then, source plugins and add commands to $PATH
zplug load --verbose

# TODO: load all files from ~/my-config/user
# source ~/my-config/user/global.zsh
if [ -f "$HOME/.cargo/env" ]; then
    source $HOME/.cargo/env
fi

if [ -f "/usr/share/chruby/chruby.sh" ]; then

    source /usr/share/chruby/chruby.sh
fi

export GO111MODULE=auto
export GOPATH=~/go
export DENO_INSTALL="$HOME/.deno"
export DPRINT_INSTALL="$HOME/.dprint"
export PATH="$PATH:/usr/lib/dart/bin"
export N_PREFIX="$HOME/n"
export PATH="$N_PREFIX/bin:$DENO_INSTALL/bin:$DPRINT_INSTALL/bin:$HOME/my-config/scripts/bin:$HOME/.local:$GOPATH/bin:$HOME/.nimble/bin:$PATH"

# Load macchina (neofetch alternative)
macchina

