source ~/.zplug/init.zsh
# zsh plugins
zplug "zplug/zplug", hook-build:"zplug --self-manage"
zplug "zsh-users/zsh-completions"
zplug "zsh-users/zsh-autosuggestions"
zplug "zsh-users/zsh-syntax-highlighting"
zplug "Aloxaf/fzf-tab"
# Load zsh plugins
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

export SHELL=$(which zsh)

if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
    source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Neovim ftw
export EDITOR="nvim"
export VISUAL="$EDITOR"
export GIT_EDITOR="$EDITOR"
export TERMINAL="alacritty"
# Aliases
alias lsa="ls -a"
alias nnn="nnn -Rdae"
alias ll="nnn"
alias N='sudo -E nnn'

## Git alias shortcuts
alias g="git"
alias gbr="git branch"
alias gps="git push"
alias gpl="git pull"
alias gc="git commit"
alias gcam="git commit -a -m"
alias gst="git status"
alias gdf="git diff"
alias gad="git add"
alias gch="git checkout"
alias gchb="git checkout -b"
alias gl=" git log --graph --abbrev-commit --date=local --name-status"
# Open git repo url in browser
alias gro="xdg-open $(git remote get-url origin)"

# ptSh
alias ls="ptls"
alias pwd="ptpwd"
alias mkdir="ptmkdir"
alias touch="pttouch"
alias cp="ptcp"

#source ./keybindings.sh

# TODO: load all files from ~/my-config/user
# source ~/my-config/user/global.zsh
if [ -f "$HOME/.cargo/env" ]; then
    source $HOME/.cargo/env
fi

if [ -f "/usr/share/chruby/chruby.sh" ]; then

    source /usr/share/chruby/chruby.sh
fi

export GO111MODULE=auto
export GOPATH=~/go
export DENO_INSTALL="$HOME/.deno"
export DPRINT_INSTALL="$HOME/.dprint"
export PATH="$PATH:/usr/lib/dart/bin"
export N_PREFIX="$HOME/n"
export PATH="$N_PREFIX/bin:$DENO_INSTALL/bin:$DPRINT_INSTALL/bin:$HOME/my-config/scripts/bin:$HOME/.local/bin:$GOPATH/bin:$HOME/.nimble/bin:$HOME/.local/bin/kt-server/bin:$HOME/.cargo/bin:$HOME/bin:$PATH"
# Homebrew
export PATH="$HOME/usr/local/bin:$HOME/usr/local/opt:$PATH"
# nnn (cli file browser)
export NNN_PLUG="t:_|alacritty*;v:preview-tabbed"
export NNN_USE_EDITOR=1

# Load macchina (neofetch alternative)
macchina -H kernel

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# tabtab source for packages
# uninstall by removing these lines
[[ -f ~/.config/tabtab/zsh/__tabtab.zsh ]] && . ~/.config/tabtab/zsh/__tabtab.zsh || true

# Starship prompt
if command -v starship; then
    eval "$(starship init zsh)"
fi
zplug load --verbose
#compdef boop
###-begin-boop-completions-###
#
# yargs command completion script
#
# Installation: boop completion >> ~/.zshrc
#    or boop completion >> ~/.zsh_profile on OSX.
#
_boop_yargs_completions()
{
  local reply
  local si=$IFS
  IFS=$'
' reply=($(COMP_CWORD="$((CURRENT-1))" COMP_LINE="$BUFFER" COMP_POINT="$CURSOR" boop --get-yargs-completions "${words[@]}"))
  IFS=$si
  _describe 'values' reply
}
compdef _boop_yargs_completions boop
###-end-boop-completions-###

GO111MODULE=on
alias luamake=$HOME/build/lua-language-server/3rd/luamake/luamake

