<<<<<<< Updated upstream
font_family JetBrainsMono Nerd Font
font_size 18.0
||||||| constructed merge base
font_family FiraCode Nerd Font
font_size 18.0
=======
font_family FiraCode Nerd Font
font_size 16.0
>>>>>>> Stashed changes
shell zsh
foreground #DDDDDD
background #111418
background_opacity 0.8
