# GPU
vo=vaapi
gpu-api=vulkan
vulkan-async-compute=yes
vulkan-async-transfer=yes
hwdec=vaapi
fbo-format=rgba16f
dscale=mitchell
sigmoid-upscaling=yes
cscale=mitchell
linear-downscaling=no

# Subtitles
blend-subtitles=yes

# Motion
override-display-fps=60
video-sync=display-resample
interpolation=yes
tscale=oversample

demuxer-cache-wait=yes
demuxer-max-bytes=4MiB

script-opts=ytdl_hook-ytdl_path=yt-dlp

